version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:3000"  # Map host port 80 to container port 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules