apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2-deployment
  labels:
    app: microservice2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
        - name: microservice2
          image: newusername/microservice2:v1   # Replace with your Docker Hub image
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
