apiVersion: v1
kind: Service
metadata:
  name: microservice2-service
spec:
  selector:
    app: microservice2
  type: LoadBalancer   # Use NodePort if LoadBalancer is not available
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 5000  # Container port
